name: deploy docs

on:
  push:
    branches:
      - main

jobs:
  docs-deploy:
    name: Deploy docs to webpage
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
         release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install glacier
        run: dart pub global activate glacier

      - name: Generate docs
        run: dart pub global run glacier generate

      - name: Deploy nyxx dev docs
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_SERVER_KEY }}
          ARGS: "-rltDzvO"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.DEPLOY_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_REMOTE_USER }}
          TARGET: "${{ secrets.DEPLOY_REMOTE_TARGET }}/"
